"""
generator_manager.py
====================
Generator component registry and GeneratorManager.

To add a new Generator:
  1. Implement it in this directory (goldenverba/components/generation/)
  2. Import it below and add an instance to the generators list

VERBA_PRODUCTION env var
------------------------
When set to "Production", local-only generators (Ollama, Groq, Novita AI) are
excluded. This is used for hosted deployments where those services aren't available.
"""

import os

from wasabi import msg

from goldenverba.components.interfaces import Generator

from goldenverba.components.generation.CohereGenerator import CohereGenerator
from goldenverba.components.generation.AnthrophicGenerator import AnthropicGenerator
from goldenverba.components.generation.OllamaGenerator import OllamaGenerator
from goldenverba.components.generation.OpenAIGenerator import OpenAIGenerator
from goldenverba.components.generation.GroqGenerator import GroqGenerator
from goldenverba.components.generation.NovitaGenerator import NovitaGenerator
from goldenverba.components.generation.UpstageGenerator import UpstageGenerator
from goldenverba.components.generation.DeepSeekGenerator import DeepSeekGenerator
from goldenverba.components.generation.LMStudioGenerator import LMStudioGenerator

try:
    import tiktoken
except Exception:
    msg.warn("tiktoken not installed, your base installation might be corrupted.")

# Local-only generators are excluded in Production mode (hosted deployments)
_is_production = os.getenv("VERBA_PRODUCTION") == "Production"

generators = [
    g for g in [
        OllamaGenerator(),
        OpenAIGenerator(),
        AnthropicGenerator(),
        CohereGenerator(),
        GroqGenerator(),
        NovitaGenerator(),
        UpstageGenerator(),
        DeepSeekGenerator(),
        LMStudioGenerator(),
    ]
    # OllamaGenerator, GroqGenerator, NovitaGenerator excluded in Production
    if not _is_production or g.name not in {"Ollama", "Groq", "Novita AI"}
]


class GeneratorManager:
    """Dispatches generate_stream() calls to the correct Generator implementation."""

    def __init__(self):
        self.generators: dict[str, Generator] = {
            generator.name: generator for generator in generators
        }

    async def generate_stream(self, rag_config, query, context, conversation):
        """Generate a stream of response dicts based on a list of queries and list of contexts, and includes conversational context
        @parameter: queries : list[str] - List of queries
        @parameter: context : list[str] - List of contexts
        @parameter: conversation : dict - Conversational context
        @returns Iterator[dict] - Token response generated by the Generator in this format {system:TOKEN, finish_reason:stop or empty}.
        """

        generator = rag_config["Generator"].selected
        generator_config = (
            rag_config["Generator"].components[rag_config["Generator"].selected].config
        )

        if generator not in self.generators:
            raise Exception(f"Generator {generator} not found")

        async for result in self.generators[generator].generate_stream(
            generator_config, query, context, conversation
        ):
            yield result

    def truncate_conversation_dicts(
        self, conversation_dicts: list[dict[str, any]], max_tokens: int
    ) -> list[dict[str, any]]:
        """
        Truncate a list of conversation dictionaries to fit within a specified maximum token limit.

        @parameter conversation_dicts: List[Dict[str, any]] - A list of conversation dictionaries that may contain various keys, where 'content' key is present and contains text data.
        @parameter max_tokens: int - The maximum number of tokens that the combined content of the truncated conversation dictionaries should not exceed.

        @returns List[Dict[str, any]]: A list of conversation dictionaries that have been truncated so that their combined content respects the max_tokens limit. The list is returned in the original order of conversation with the most recent conversation being truncated last if necessary.

        """
        encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
        accumulated_tokens = 0
        truncated_conversation_dicts = []

        # Start with the newest conversations
        for item_dict in reversed(conversation_dicts):
            item_tokens = encoding.encode(item_dict["content"], disallowed_special=())

            # If adding the entire new item exceeds the max tokens
            if accumulated_tokens + len(item_tokens) > max_tokens:
                # Calculate how many tokens we can add from this item
                remaining_space = max_tokens - accumulated_tokens
                truncated_content = encoding.decode(item_tokens[:remaining_space])

                # Create a new truncated item dictionary
                truncated_item_dict = {
                    "type": item_dict["type"],
                    "content": truncated_content,
                    "typewriter": item_dict["typewriter"],
                }

                truncated_conversation_dicts.append(truncated_item_dict)
                break

            truncated_conversation_dicts.append(item_dict)
            accumulated_tokens += len(item_tokens)

        # The list has been built in reverse order so we reverse it again
        return list(reversed(truncated_conversation_dicts))
